version: "3"

services:
  app:
    build: .
    container_name: api-com-loopback-app-test
    entrypoint: ./.docker/entrypoint.sh
    ports:
      - 3000:3000
    volumes:
      - .:/home/node/app
    depends_on:
      - db

  db:
    image: mysql:5.7
    container_name: api-com-loopback-db-test
    restart: always
    tty: true
    ports:
      - "33006:3306"
    volumes:
      - ./.docker/dbdata:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=api_com_loopback_test
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=root
